name: najot_shop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'



dependencies:
  flutter:
    sdk: flutter


  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3
  firebase_auth: ^4.7.1
  firebase_storage: ^11.2.5
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  zoom_tap_animation: ^1.1.0
  provider: ^6.0.5
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
#    - assets/images/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Borel
      fonts:
        - asset: assets/fonts/Borel-Regular.ttf